import type { NextPage } from "next";
import Head from "next/head";
import Header from "../src/components/Header";
import UserProfileMinimal from "../src/components/UserProfileMinimal";
import { User } from "../src/interface";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const users: User[] = [
    { name: "Le Van Tu", age: "20" },
    { name: "Truong Quang Tu", age: "40" },
  ];

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />

        {users.map((user) => (
          <UserProfileMinimal userData={user} key={user.name} />
        ))}
      </main>
    </div>
  );
};

export default Home;
