import type { NextPage } from "next";
import Head from "next/head";
import FullControlledHeader from "../src/components/common/FullControlledHeader";
import UserProfileMinimal from "../src/components/pages/home/UserProfileMinimal";
import { User } from "../src/interface";

const Home: NextPage = () => {
  const users: User[] = [
    { name: "Le Van Tu", age: "20" },
    { name: "Truong Quang Tu", age: "40" },
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <FullControlledHeader />

        {users.map((user) => (
          <UserProfileMinimal userData={user} key={user.name} />
        ))}
      </main>
    </div>
  );
};

export default Home;
